config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :homes
  # Defines the root path route ("/")
  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def create
    if params["price"].present?
    price = params["price"]
    calculate =  ((Math.sqrt(price.to_f) * 180) - 225) / 360
    value = calculate.modulo(1)
    @res = value * 360
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/create.turbo_stream.erb
<%= turbo_stream.replace 'cal_res' do %>
  <%= turbo_frame_tag 'cal_res' do%>
  <h2><%= @res %></h2>
<% end %>
<% end %>

app/views/homes/index.html.erb
<main>
  <div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-md-10 mx-auto col-lg-5">
        <%= form_for homes_path, class: "p-4 p-md-5 border rounded-3 bg-light" do %>
          <div class="form-floating mb-3">
            <%= number_field_tag 'price','', class: "form-control", placeholder: "Enter Number", required: true %>
            <label for="floatingInput">Enter Number</label>
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">Calculate</button>
        <% end %>
      </div>
    </div>
    <div class="text-center">
      <%= turbo_frame_tag 'cal_res' %>
      <h2></h2>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calculations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>